[general]
context=default
bindport=5061
bindaddr=0.0.0.0
transport=udp,tcp,tls,ws,wss
tlscertfile=/etc/asterisk/tls/asterisk.crt
tlsprivatekey=/etc/asterisk/tls/asterisk.key
tlscafile=/etc/asterisk/tls/ca.crt
videosupport=yes
encryption=yes
externip=${EXTERNAL_IP}
localnet=172.16.0.0/12

[kamailio]
type=peer
host=kamailio
port=5060
insecure=port,invite
context=from-kamailio
disallow=all
allow=ulaw
allow=alaw
allow=g722
allow=opus
